name: PR Check
on: [pull_request]
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: set up JDK 11.0.13
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11.0.13'

      - name: Make local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ADMOB_APP_ID=${{ secrets.ADMOB_APP_ID }}" >> local.properties
          echo "ADMOB_MAIN_BANNER_ID=${{ secrets.ADMOB_MAIN_BANNER_ID }}" >> local.properties
          echo "ADMOB_EDITOR_BANNER_ID=${{ secrets.ADMOB_EDITOR_BANNER_ID }}" >> local.properties
          echo "ABMOB_BNNER_TEST=${{ secrets.ABMOB_BNNER_TEST }}" >> local.properties

      - name: ktlint
        run: ./gradlew ktlintCheck
  # add unit test