name: Upload to Google Play

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11.0.13
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11.0.13'

      - name: Make local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ADMOB_APP_ID=${{ secrets.ADMOB_APP_ID }}" >> local.properties
          echo "ADMOB_MAIN_BANNER_ID=${{ secrets.ADMOB_MAIN_BANNER_ID }}" >> local.properties
          echo "ADMOB_EDITOR_BANNER_ID=${{ secrets.ADMOB_EDITOR_BANNER_ID }}" >> local.properties
          echo "ADMOB_BANNER_TEST=${{ secrets.ADMOB_BANNER_TEST }}" >> local.properties

      - name: Build with Gradle
        run: ./gradlew bundleRelease

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.yessorae.goalreminder
          releaseFiles: build/outputs/bundle/release/app-release.aab
          track: production
          whatsNewDirectory: ./whatsnew